apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
spec:
  containers:
    - command: ['sh', '-c', ' sleep 10 && echo The app is running!']
      image: busybox
      name: pods-simple-container