apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingdeployment
  labels:
    app: script
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  selector:
    matchLabels:
      app: script
  template:
    metadata:
      labels:
        app: script
    spec:
      containers:
        - image: timba/script:1.0
          name: script
